#!/bin/sh

set -e

case "$1" in
    remove|deconfigure)
        update-alternatives --quiet --remove zebraidx /usr/bin/zebraidx-2.0
        update-alternatives --quiet --remove zebrasrv /usr/bin/zebrasrv-2.0
        ;;
    *)
esac

# Automatically added by dh_installsystemd/13.24.2
if [ -z "$DPKG_ROOT" ] && [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
    deb-systemd-invoke stop 'zebrasrv.service' >/dev/null || true
fi
# End automatically added section
