# $Id: RetrievalRecord.pm,v 1.1 2003-03-03 00:45:37 pop Exp $
# 
# Zebra perl API header
# =============================================================================
package IDZebra::RetrievalRecord;

use strict;
use warnings;

BEGIN {
    use IDZebra;
    our $VERSION = do { my @r = (q$Revision: 1.1 $ =~ /\d+/g); sprintf "%d."."%02d" x $#r, @r }; 
}

# =============================================================================
# THIS IS Just the documentation, the real code is autogenerated by SWIG in
# IDZebra.pm
# =============================================================================
__END__

=head1 NAME

IDZebra::RetrievalRecord - Structure representing a retrieval record

=head1 SYNOPSIS

=head1 DESCRIPTION

=head1 PROPERTIES

=head1 COPYRIGHT

Fill in

=head1 AUTHOR

Peter Popovics, pop@technomat.hu

=head1 SEE ALSO

IDZebra, IDZebra::Session, IDZebra::Resultset, Zebra documentation

=cut

1;
